name: 'Gluon iOS release'
description: 'Action to build, sign and upload a Gluon build .ipa to TestFlight. This job MUST run on macos-latest'
inputs:
  gluon-license:
    description: 'Gluon license if available'
    required: false
  bundle-id:
    description: 'bundle id'
    required: true
  xcode-version:
    description: 'Specific xcode version.'
    required: false
    default: '11.7'
  graalvm-version:
    description: 'Specific GraalVM version.'
    required: false
    default: '20.2.0.java11'
  maven-gluon-build:
    description: 'maven command to build the ipa. leave out to use default: mvn -Pios client:build client:package'
    required: false
    default: 'mvn -Pios client:build client:package'
runs:
  using: "composite"
  steps: 
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: ${{ inputs.graalvm-version }}
    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ inputs.bundle-id }} 
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - name: Build and package as iOS application with Gluon
      run: mvn -Pios client:build client:package
      env:
        GRAALVM_HOME: /System/Volumes/Data/Users/runner/hostedtoolcache/GraalVM/${{ inputs.graalvm-version }}/x64/
    - uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: target/client/arm64-ios/*.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
