name: 'Gluon Build'
description: 'Action to build a Gluon application.'
inputs:
  gluon-license:
    description: 'Gluon license if available'
    required: false
  platform:
    description: 'The platform to build for: linux, windows, ios, android'
    required: true  
  graalvm-version:
    description: 'GraalVM version'
    required: false
    default: '20.2.0.java11'
runs:
  using: "composite"
  steps: 
    - run: printf "${{ inputs.gluon-license }}"
      shell: bash
    - run: printf "${{ inputs.gluon-license }}" > src/main/resources/gluonmobile.license
      shell: bash
    - run: cat src/main/resources/gluonmobile.license 
      shell: bash
    - run: mvn -P${{ inputs.platform }} client:build client:package
      shell: bash
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}

