name: 'Gluon Build'
description: 'Action to build a Gluon application.'
inputs:
  gluon-license:
    description: 'Gluon license if available'
    required: false
  platform:
    description: 'The platform to build for: linux, windows, ios, android'
    required: true  
runs:
  using: "composite"
  steps: 
    - run: mvn -P${{ platform }} client:build client:package
      shell: bash
      env:
        GRAALVM_HOME = ${{ JAVA_HOME }}
